apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:5.1-apache
        env:
          - name: PMA_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: database-url 
          - name: PMA_PORT 
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: database-port
          - name: PMA_ARBITRARY
            value: "1"
        resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30301 